FROM {{ base_image }}

# Install packages
{%- if 'alpine' in base_image %}
RUN apk update && apk upgrade && apk add alpine-sdk && apk add linux-headers
{%- else %}
RUN apt-get update -qq && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{%- endif %}

RUN gem install bundler

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

# Set up deploy user
{%- if 'alpine' in base_image %}
RUN adduser -D -g '' deploy
{%- else %}
RUN adduser --disabled-password --gecos '' deploy
{%- endif %}

# Set up working directory
RUN mkdir /app

# Set up gems
WORKDIR /tmp
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install -j4

# Finally, add the rest of our app's code
# (this is done at the end so that changes to our app's code
# don't bust Docker's cache)
ADD . /app
WORKDIR /app
RUN chown -R deploy:deploy /app

# Switch to deploy user
USER deploy
ENV USER deploy
ENV HOME /home/deploy

ENV PORT {{ target_port }}
EXPOSE {{ target_port }}

CMD {{ command }}

