FROM {{ base_image }}

# Install packages
{%- if 'alpine' in base_image %}
RUN apk update && apk upgrade && apk add alpine-sdk && apk add linux-headers
{%- else %}
RUN apt-get update -qq && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{%- endif %}

# Set up deploy user
{%- if 'alpine' in base_image %}
RUN adduser -D -g '' deploy
{%- else %}
RUN adduser --disabled-password --gecos '' deploy
{%- endif %}

# Set up working directory
RUN mkdir /app

RUN npm install -g yarn

# Set up node modules
WORKDIR /tmp
ADD package.json package.json
ADD yarn.lock yarn.lock
RUN yarn install
RUN mv /tmp/node_modules /app/

# Finally, add the rest of our app's code
# (this is done at the end so that changes to our app's code
# don't bust Docker's cache)
ADD . /app
WORKDIR /app
RUN chown -R deploy:deploy /app

# Switch to deploy user
USER deploy
ENV USER deploy
ENV HOME /home/deploy

ENV PORT {{ target_port }}
EXPOSE {{ target_port }}

CMD {{ command }}

