FROM {{ base_image }}

# Install packages
{%- if 'alpine' in base_image %}
RUN apk update && apk upgrade && apk add alpine-sdk && apk add linux-headers
{%- else %}
RUN apt-get update -qq && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{%- endif %}

# Set up deploy user
{%- if 'alpine' in base_image %}
RUN adduser -D -g '' deploy
{%- else %}
RUN adduser --disabled-password --gecos '' deploy
{%- endif %}

RUN mix local.hex --force
RUN mix local.rebar --force

# Set up working directory
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN chown -R deploy:deploy /app

# Switch to deploy user
USER deploy
ENV USER deploy
ENV HOME /home/deploy

ENV PORT {{ target_port }}
EXPOSE {{ target_port }}

RUN mix deps.get
RUN mix compile

CMD {{ command }}

