FROM {{ base_image }}

{%- if 'alpine' in base_image %}
RUN apk update && apk upgrade && apk add alpine-sdk && apk add linux-headers
{%- else %}
RUN apt-get update -qq && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{%- endif %}

# Set up working directory
RUN mkdir /app

ADD . /app
WORKDIR /app

RUN npm install --production

ENV PORT {{ target_port }}
EXPOSE {{ target_port }}

CMD {{ command }}

