FROM {{ base_image }}

{%- if 'alpine' in base_image %}
RUN apk update && apk upgrade && apk add alpine-sdk && apk add linux-headers
{%- else %}
RUN apt-get update -qq && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{%- endif %}

RUN mix local.hex --force
RUN mix local.rebar --force

# Set up working directory
RUN mkdir /app
ADD . /app
WORKDIR /app

ENV PORT {{ target_port }}
EXPOSE {{ target_port }}

RUN mix deps.get
RUN mix compile

CMD {{ command }}

